### ISSUE TITLE
Составить интро

### ISSUE THREAD

**Issue by La-7** [La-7/homepage#4]
Составить интро (вступление), где в 2-4 предложениях описать, что заказчик делает, что нравится делать, что хочется делать лучше, что важно делать, и т.д.

**Comment by Sagittaril** [comment]
I'm the most successful person ever by far. Nobody's ever been more successful than me. I'm the most successful person ever to run. Vladimir Putin isn't successful like me. Sorry losers and haters, but my IQ is the highest ― and you all know it! Please don't feel so stupid or insecure, it's not your fault.
