### ISSUE TITLE
Составить блок контактной информации

### ISSUE THREAD

**Issue by La-7** [La-7/homepage#5]
Ссылки на соцсети (Facebook или Instagram, и т.п.), номер телефона или адрес электронной почты, т.п. Может не все ссылки в мире, а только те, которые действительно уместны.

**Comment by Sagittaril** [comment]
https://twitter.com/synPodrygiMamy
https://www.instagram.com/thesonofafriendofmymother/
https://www.facebook.com/profile.php?id=100067121869625
