### ISSUE TITLE
Составить таймлайн

### ISSUE THREAD

**Issue by La-7** [La-7/homepage#6]
Составить список всех (важных) жизненных событий, памятных дат, достижений, периодов, которые дали приятный и неприятный опыт, и т.п. В этом конкретном случае длинных списков не бывает, бывают плохо свернутые, поэтому пакуем сюда всё подряд, а про "лишние" события можно будет промолчать позже. Список должен быть систематизирован и отсортирован таким образом, чтоб читатель быстро понял "паттерн" и мог легко ориентироваться в пространстве и времени этого резюме.

**Comment by Sagittaril** [comment]
EXPERIENCE

2020
Some problem started on Earth without me.
Visited Mars.

2019
Helped Elon Musk with his rockets.
Helped the Ukrainian youth team to win the World Youth Championship.
Flew to Mars at the end of the year.

2018
Created "My mother's friend's son" University: no grades, certificates and other bureaucracy, but program offered courses how to become like me. 100% students gave positive reviews while studying, however no one became like me. 

2017
Became first president of the world.
Acquired the half of the country in which I was born.

2016
Won election race with 100% votes more than my opponents, kchauuuuuu!

2015
Became the most important human.

PERSONAL LIFE

2019
Birth of My mother's friend's son's daughter

2018
My first son is born. I called him My mother's friend's son's son, of course!

2018
Married the best woman of the world

MEDIA CAREER

2019
Won an Oskar and Golden Globe for my role as a my mom's friend's son in the best film of all time.

2018
Published a book "Midas Touch: Hot To Become Poorer - Give Money To Me "

2017
Received a star on the Hollywood Walk of Fame for being myself

2016
Published a book "Think Like the My mother's friend's son: Everything You Need to Know About Success, Real Estate, and Life".

2015
Published a book "The Best Boys Quotations Advice I Ever Seen In Boys Channels"

EDUCATION

2016
Friends and the US government give me the status of the best student in the world 

2014
Transferred to MIT

2012
Started studying in Harvard University 

2007
Enrolled in Imperial College London
